services:
  - type: web
    name: conjointlab
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: conjoint-db
          property: connectionString

databases:
  - name: conjoint-db
    plan: free
